name: mind_palace_json_storage
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  json_annotation: ^4.9.0
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
